package com.game.frame.scene;

/**
 * Created by fangxg on 2016/9/27.
 */

public enum SCENE_ID {
    LOGO_1,
    LOGO_2,
    LOGO_3,
    BEGIN_MENU,
    DIFF_MENU,
    LOAD_GAME,
    SAVE_GAME,
    SETTING,
    BEGIN_LOCAL,
    BEGIN_COUNTY,
    SELECT_TARGET,
    TEAM_BUILD,
    WEAPON_BUY,
    WEAPON_REPAIR,
    DIPLOMACY,
    WEAPON_SELL,

    BATTLEFIELD_ENTER_INFO,
    BATTLEFIELD_ENTER_INFO_HUD,
    TUTORIAL,
    BATTLEFIELD,
    BATTLEFIELD_HUD,

    WEAPON_SETOUT,

    BATTLEFIELD_INFO,
    TEAM_LIST,

    CHAPTER_COMPLETE,
    CHAPTER_LOSE,

    CAN_BUY_WEAPON_DIALOG,
    LV_UP_DIALOG,
    CAPTURE_DIALOG,
    YES_NO_DIALOG,
    BLUE_REPAIR_YES_NO_DIALOG,
    GET_SOME_THING_DIALG,
    DIALOG_5_DIALOG,
    TURN_BEGIN_DIALG,
    AI_REPAIR_NEXT_DIALOG,

    FLAGS_SUB,
    SORT_MENU,
    SORTS_SUB,
    SYSTEM_POPUP_MENU,
    TOP_BUTTOS_SUB,
    BORDER_SUB,
    TOP_MENU,
    CHOOSE_ARMS_MENU,

    DEBUG_DIALOG_MAIN_DIALOG,
    DEBUG_DIALOG_1_DIALOG,
    DEBUG_DIALOG_2_DIALOG,
    DEBUG_DIALOG_3_DIALOG,
}
